server:
    port: 8080

# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar quartz-service.jar --spring.profiles.active=test
#   生产环境：java -jar quartz-service.jar --spring.profiles.active=prod
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=DataCenter
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 111
  redis:
    hostName: 127.0.0.1
    port: 6379
    database: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -2


mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*Mapper.xml    #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
 # typeAliasesPackage: com.kwantler.task.entity.*         #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
logging:
  file: quartz-service.log
  level:
    com.quartz: debug

