
package com.kwantler.interchange.wsdl.service.invoke.hello;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JwsServiceHello", targetNamespace = "http://hello.service.wsdl.interchange.kwantler.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JwsServiceHello {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://hello.service.wsdl.interchange.kwantler.com/", className = "com.kwantler.interchange.wsdl.service.hello.clientInvoke.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://hello.service.wsdl.interchange.kwantler.com/", className = "com.kwantler.interchange.wsdl.service.hello.clientInvoke.GetValueResponse")
    @Action(input = "http://hello.service.wsdl.interchange.kwantler.com/JwsServiceHello/getValueRequest", output = "http://hello.service.wsdl.interchange.kwantler.com/JwsServiceHello/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.kwantler.interchange.wsdl.service.hello.clientInvoke.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://hello.service.wsdl.interchange.kwantler.com/", className = "com.kwantler.interchange.wsdl.service.hello.clientInvoke.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://hello.service.wsdl.interchange.kwantler.com/", className = "com.kwantler.interchange.wsdl.service.hello.clientInvoke.GetUsersResponse")
    @Action(input = "http://hello.service.wsdl.interchange.kwantler.com/JwsServiceHello/getUsersRequest", output = "http://hello.service.wsdl.interchange.kwantler.com/JwsServiceHello/getUsersResponse")
    public List<User> getUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
